CREATE TABLE IF NOT EXISTS spring_user
(
    id bigint NOT NULL generated by default as identity,
    password varchar(120) not null,
    username varchar(120) not null,
    CONSTRAINT spring_user_pkey PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS spring_roles
(
    id integer NOT NULL generated by default as identity,
    name varchar(20) not null,
    CONSTRAINT spring_roles_pkey PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS public.spring_user_roles
(
    user_id bigint NOT NULL,
    role_id integer NOT NULL,
    CONSTRAINT spring_user_roles_pkey PRIMARY KEY (user_id, role_id),
    CONSTRAINT spring_user_roles_fk_users FOREIGN KEY (user_id)
        REFERENCES spring_user (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT spring_user_roles_fk_roles FOREIGN KEY (role_id)
        REFERENCES spring_roles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

CREATE TABLE IF NOT EXISTS spring_register_login
(
    id integer NOT NULL generated by default as identity,
    login_name varchar(120) not null,
    observation varchar(1000),
    password varchar(1000) not null,
    CONSTRAINT spring_register_login_pkey PRIMARY KEY (id)
)

insert into spring_roles (id, name) VALUES (1, 'ROLE_ADMIN')
insert into spring_roles (id, name) VALUES (2, 'ROLE_USER')